remote_theme: "owasp/www--site-theme"

#override default star and watch buttons
github:
  code_user: zaproxy
  code_repo: zaproxy

# core files/folders to exclude
exclude:
 - README.md

plugins:
 - jekyll-include-cache-0.2.0